class 'NetworkEvents'

function NetworkEvents:__init()
  Events:Subscribe("NE:Broadcast", self, self.BroadcastHandler)
  Network:Subscribe("NE:Subscribe", self, self.SubscribeHandler)
end

-- list of client events that are handled in this module
NetworkEvents.moduleHandlesClientEvents={} 


--- Network::Broadcast replacement, that allows cross-module communication
-- works by transmitting this as event to all modules with NetworkEvents script
-- which then retransmit them to clients using NetworkEvents.BroadcastHandler
-- @todo maybe transmitting first to client-side, and then to willing to handle modules would be faster?
function NetworkEvents.Broadcast(self,name,data)
  -- send to other modules, server-side
  Events:Fire("NE:Broadcast", {name=name, data=data})
end


--- Network::Send replacement, that allows cross-module communication
-- works by transmitting this as event to all modules with NetworkEvents script
-- which then retransmit them to client using NetworkEvents.SendHandler
-- @todo maybe transmitting first to client-side, and then to willing to handle modules would be faster?
function NetworkEvents.Send(self,player,name,data)
  -- send to other modules, server-side
  Events:Fire("NE:Send", {name=name, data=data})
end

--- Events::Subscribe replacement, allowing script to register itself as willing
-- to accept client-server communication for given event name.
function NetworkEvents.Subscribe(self, eventName)
  Network:Broadcast("NE:Subscribe", eventName)
end


--- Event Handler: Receives Broadcast events from other modules and transmit them to 
-- clients, if any of them is willing to handle
function NetworkEvents.BroadcastHandler(self,data)
  if not self.moduleHandlesClientEvents[data.name] then 
    return 
  end
  Network:Broadcast(data.name, data.data)
end


--- Event Handler: Receives Send events from other modules and transmit them to 
-- clients, if any of them is willing to handle
function NetworkEvents.SendHandler(self,data)
  if not self.moduleHandlesClientEvents[data.name] then 
    return 
  end
  Network:Broadcast(data.name, data.data) -- @todo direct to one player! @fixme
end


--- Network handler: registers server->client events being handled in this module
-- handles events generated by NetworkEventsClient:Subscribe
function NetworkEvents.SubscribeHandler(self, arg)
  if not arg or type(arg)~="string" then return end
  self.moduleHandlesClientEvents[arg]=true
end

--- Initialized server-side NetworkEvents instance
NetworkEvents=NetworkEvents()
